version: '3.7'

services:
  config:
    container_name: config
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
    command: >
      bash -c "echo 'starting config'
      && java -Xmx100m -jar /home/libs/config-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    restart: always
    expose:
      - 3100
    ports:
      - "3100:3100"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    container_name: registry
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting registry'
      && sh /usr/bin/wait_for_service.sh config:3100 5
      && java -Xmx100m -jar /home/libs/registry-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3101
    ports:
      - "3101:3101"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    container_name: gateway
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting gateway'
      && sh /usr/bin/wait_for_service.sh registry:3101 5
      && java -Xmx100m -jar /home/libs/gateway-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3102
    ports:
      - "3102:3102"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user:
    container_name: user
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting user'
      && sh /usr/bin/wait_for_service.sh gateway:3102 5
      && java -Xmx100m -jar /home/libs/user-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3103
    ports:
      - "3103:3103"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  authorization:
    container_name: authorization
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting authorization'
      && sh /usr/bin/wait_for_service.sh user:3103 5
      && java -Xmx100m -jar /home/libs/authorization-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3104
    ports:
      - "3104:3104"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  catalog:
    container_name: catalog
    image: pluribuslabs/centos7-oracle-jdk-8
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting catalog'
      && sh /usr/bin/wait_for_service.sh gateway:3102 5
      && java -Xmx100m -jar /home/libs/catalog-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3105
    ports:
      - "3105:3105"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'elibrary'
      MYSQL_USER: 'elibraryapp'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'l1ghTs_0Ff'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    #      - ./mysql/elibrary_dump.sql:/docker-entrypoint-initdb.d/elibrary_dump.sql
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  mysql_db_data_container: