version: '2.2'

services:
  config:
    container_name: config
    image: openjdk:oraclelinux7
    volumes:
      - ./build/libs:/home/libs
    command: >
      bash -c "echo 'starting config'
      && java -Xmx100m -jar /home/libs/config-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    restart: always
    expose:
      - 3100
    ports:
      - "3100:3100"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    container_name: registry
    image: openjdk:oraclelinux7
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting registry'
      && sh /usr/bin/wait_for_service.sh config:3100 5
      && java -Xmx100m -jar /home/libs/registry-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3101
    ports:
      - "3101:3101"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    container_name: gateway
    image: openjdk:oraclelinux7
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting gateway'
      && sh /usr/bin/wait_for_service.sh registry:3101 5
      && java -Xmx100m -jar /home/libs/gateway-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3102
    ports:
      - "3102:3102"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user:
    container_name: user
    image: openjdk:oraclelinux7
    volumes:
      - ./build/libs:/home/libs
      - ./wait_for_service.sh:/usr/bin/wait_for_service.sh
    command: >
      bash -c "echo 'starting user'
      && sh /usr/bin/wait_for_service.sh gateway:3102 5
      && java -Xmx100m -jar /home/libs/user-0.1.0.jar"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    expose:
      - 3103
    ports:
      - "3103:3103"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
