server:
  port: 3104

security:
  client-id: elibrary-client
  client-secret: elibrary-secret
  access-token-expiration: 15
  refresh-token-expiration: 30
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgB0moU7+2ci63mF7dBQ+PIK
    QTscZj7S46sKB7NKwkeLWuJcr3C7ZwSBeA89Y6fdpcZhd914Yk38UKDHK9u7UbfP
    vOBhNKD2WweN5T5Y5oHZO50rv+1GzC7VRdpDfuRMwMkxABqNnlkgDJlijhnXEvOc
    lFywHIIyW6IfJvYUV+uhoSqaSZTqkPn8nPMV0WXfnGpjX0E/VTOVy+2g5Ki7tkZ/
    HS6F45S9KZQc5rbVa0oy5bRsTgBfO98Fe7zod1sDZarYGIrdq8tolOrNbetu49Ba
    44ENowulBrnklpAHUp1kf/Q1M5dr9UBR/qTaV79AUvEHrks6Chpt5e8YodfNDsIg
    NUU4N6yh2NcdahN9BkTyQGFasTuv7Df6s3uOxhk8cHEajQ/mmRWr0PkO4yUtzUJm
    XMdOMkwbCnLmpJqYTYXyMS+7Bv5b3gcGvDyDRd6DC9QvjR/WxAN3s84FKeV9K0N8
    9STaGF2MDedI6sNAi4fo1T6WrTPwp6NmRMrxGy07HT5X2X0GXo0xgseixRZ6VbZT
    SCyxh0xqpuxiyevU0+Br9CFHbpTjMs6aa9dltlHmbVoRMIXUC3HMyIORYdqk6NJ7
    gB0ToxlRM8vcDG1pu3n59aTJuAQHgq0RZpDuiOFvU7VgzPdmFr+rLi3yZ5UkmB9T
    lM97Ex0MlED38Asau9B1WQIDAQAB
    -----END PUBLIC KEY-----
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJJwIBAAKCAgB0moU7+2ci63mF7dBQ+PIKQTscZj7S46sKB7NKwkeLWuJcr3C7
    ZwSBeA89Y6fdpcZhd914Yk38UKDHK9u7UbfPvOBhNKD2WweN5T5Y5oHZO50rv+1G
    zC7VRdpDfuRMwMkxABqNnlkgDJlijhnXEvOclFywHIIyW6IfJvYUV+uhoSqaSZTq
    kPn8nPMV0WXfnGpjX0E/VTOVy+2g5Ki7tkZ/HS6F45S9KZQc5rbVa0oy5bRsTgBf
    O98Fe7zod1sDZarYGIrdq8tolOrNbetu49Ba44ENowulBrnklpAHUp1kf/Q1M5dr
    9UBR/qTaV79AUvEHrks6Chpt5e8YodfNDsIgNUU4N6yh2NcdahN9BkTyQGFasTuv
    7Df6s3uOxhk8cHEajQ/mmRWr0PkO4yUtzUJmXMdOMkwbCnLmpJqYTYXyMS+7Bv5b
    3gcGvDyDRd6DC9QvjR/WxAN3s84FKeV9K0N89STaGF2MDedI6sNAi4fo1T6WrTPw
    p6NmRMrxGy07HT5X2X0GXo0xgseixRZ6VbZTSCyxh0xqpuxiyevU0+Br9CFHbpTj
    Ms6aa9dltlHmbVoRMIXUC3HMyIORYdqk6NJ7gB0ToxlRM8vcDG1pu3n59aTJuAQH
    gq0RZpDuiOFvU7VgzPdmFr+rLi3yZ5UkmB9TlM97Ex0MlED38Asau9B1WQIDAQAB
    AoICAExkxC+lKVAmiEqnoRi70Q/I5upXToeqY2/B1cR//pGdbLqesrQE7V3Jg+qL
    dPpxVsSa3H23ojJRvNRgtqhGBLBUpYjqCx78Srm7XJqwApiJRxLXvqPouDJAfpxD
    8V0b3XR+BeeMvAWUW5XHVcSkBPkr9oHnW6GUiWXxh72SUK1nQtsspCT98NqBFX3Q
    3/adqtIKIVxV/OMCZWBJDwdUh2FWhBlyHgvExuYcfeLbVRR9jDR88h9ywU39YKnJ
    MNbL8B9+DNTobe7Jyf/nKR1Qojw5215M2R84hefugNRbWwTyE9QbRfSUDJzrwaPP
    Y1zIOmP23BBdeC1SPNCdkB4nsiS2yMVV3Jaqg2xHcEy8IWFHjL0ak+AuHZ/I+H1Z
    rYk9q+4Lnk+lrcqY+4q+wDUh3ub8tIunYg1KqRsNfaY/Twf0f34eTvN/T507muqT
    RY9ZXiJ77VBYg0BKLoVwwQqtHshRqpQnTe+nujwzjqohM62caf2ItgxNND2Z2TzA
    0+8/pL98BT9Kf1ySU0fC6bF5tYK2jKdDRRTGsOo9Ux4FhDPtCXc8/ARCApaGomV8
    tdTZMAlDlmEI1bqZoADgMkJp/5xpkS3TgfqmxhMMoQVoskqhmkBg6DZ7sR2Px5Hz
    ZJsap+eGJMu3YTeG+cWgRPvEOGssG0rpiD6KMrCWOl+2WgSRAoIBAQC6/RjB0iOD
    ZBdI94aWBSUXoQbE7DlVRs3WQUM3q7yh8T1IrBbE19fyinfeaCktD+oXR37yhUCh
    n9FERGYfBMkpidqMZBU/uLpl5GU/SWTmWh74A74N2N0Sv+Vd+Q7wsAVY5J2nkWWE
    Dudfx/c2VZZtSwpP+T8ie4QDliMHQCsIL6EBAm0B0PGAPc1Z0ewaKRqcx1FwVMo9
    Fujwhwwyey2y4KFXGsbmTpfKpM1IOFAYocOlv8bDZnvm76U0GWYO6UhmvpNyLpAh
    9x1o3h6N4el9wUS3i5+fJhX2mhmCnn8qmHSTBygil0T707HDdUszhPfsOBTm08ju
    wLPyHuH7UQVFAoIBAQCfo1yx0Ocw2MCtHFfb0CHpoQ1UFsglnQHTRm6sQF8k82DN
    bfIu90+M84+hK2Q2MExTW7ZNuWLtn+9vZKHTFYdUyl4zFdmdjc9+M2adWrnbM9ez
    1ZRmIcZv3Kt40bed6nci/GGP5t+bnok0cNJW67ltQRBAFqJC5PWBllr1df8rgVli
    GDbtbb0zWh4S0ksQ1p6qOCEQQfsyEjCQ6i4xcorSAcyigjGhqlU5GQE9R4RRpmtk
    JwkhZHv/c2/49WS4wsVHo3CJQSVWfNg8i0TZEDmbuO/8rki7E3NePNqlpXLwvv4p
    ED35/scIstwHQTIZBMydn8UcS2kD25oojw/yuB8FAoIBADaXumisL44m5N161yJp
    siCp9M39oeeR2nrZZwST8Wjeg+P5ylQCKJw5bTHT+2Gaqd/OEfRAj1Qg0vo5dg9M
    WGb2RoaCmemWx2UEP8MwbHMMkMocXZqxXCojOJYtJv2Chq0jYhwQSTE7ILZILZcB
    ef/Czun2fUZWBX7+kI+HXojvTvR6ftTu6fNlF9VHgsVIhuqLDu3a84jObYf8BcWf
    TQJSrwg9WyDWhV62qvCQ8GGgqPx1d1SJUVdlVDhXygJEfczxix7lFVO1UDLT1tvZ
    v0/l42grLZlLh1IOP7BxEfOfuzlJ95/RxmQ3tEi6sBAEnFWtMf0KjDmYrXDdL2Eu
    kHkCggEAE08YLC3feOoOzCGMgvr2zyJ60Tv8M4h9Kwfu5QjYOUjy4YY17/Zb+emP
    6uertF49LSv/rgEJdUKOHIQoirak6t2bbURsUQFRIqum8suBhYEMyyS/UWcucGNZ
    nkCHnCM7C9FJH7XGQDV51Qz8dCUJBa0EASx7remxxF3iXKRMHAAGRrY1FpzacLaq
    wo4LJFtBT8eAQE4qyxCmLTEWK0b2gZZUISfsRuiqbECZBMd8ur+NZ8zM7uwPj4Nv
    /MX5y9tLL3IWb5Ogp4hsQ055ImQzA6Hn7UFLbM1afACSVczgTTxc06yyQmXNv0Cb
    GomJPLt24G3t0pFQf3X1fIhpXmtk3QKCAQEAqGQNnTBlSXlFr7MA17a5Am0aFqRY
    9kbj1/Oc+PjqfRgYKcEmnnAveOL6emJKXudAO7pnY9k/JvlFftJCK9Z7YDzLHRPM
    2AZIzdEsQPi+cAMjOxAnZxVlXJ+cBI2ZBjgfqP0UbuLXZ7LxNTmFjb0NWJI4x2dY
    61QEQekesW9kmc8XakdlLg71/96lBvnzY6j+feoovZUMhiyRmWXEqYxkZbK9dweK
    hRwn/bS99OVeGU1lVq01qXcZYScbZI7NQFKKnD3Cq5N7lJxA0pmt+E2nL18wicx4
    6WU4bgWEAKf2UjXlU3KPsySMhSkDCh0QF44MA3CHnmK+bGrhBRQcfGOzvQ==
    -----END RSA PRIVATE KEY-----