server:
  port: 3105

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/elibrary
    username: root
    password: B1KE_freeride51
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-db:3306/elibrary
    username: elibraryapp
    password: password