server:
  port: 3102

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    users:
      path: /api/users/**
      url: http://localhost:3103/api/users
    login:
      path: /api/login/**
      url: http://localhost:3104/oauth/token
    catalog:
      path: /api/catalog/**
      url: http://localhost:3105/api/catalog
    cart:
      path: /api/cart/**
      url: http://localhost:3106/api/cart

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:3104/oauth/public

---

spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:3104/oauth/public

zuul:
  routes:
    users:
      path: /api/users/**
      url: http://user:3103/api/users
    login:
      path: /api/login/**
      url: http://authorization:3104/oauth/token
    catalog:
      path: /api/catalog/**
      url: http://catalog:3105/api/catalog
    cart:
      path: /api/cart/**
      url: http://cart:3106/api/cart
