server:
  port: 3102

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    users:
      path: /api/users/**
      url: http://localhost:3103/api/users
    login:
      path: /api/login/**
      url: http://localhost:3104/oauth/token

---

spring:
  profiles: docker

zuul:
  routes:
    users:
      path: /api/users/**
      url: http://user:3103/api/users
    login:
      path: /api/login/**
      url: http://authorization:3104/oauth/token